// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpwlkkugcuewbmwwjllh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wd2xra3VnY3Vld2Jtd3dqbGxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4OTI1MDEsImV4cCI6MjA3MDQ2ODUwMX0.ecJGXhgDpYzaLQML9RYDKrxYlYv3YvordR8VvwlDxig";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});